import type { Metadata } from "next";
import { GeistSans } from "geist/font";
import { Layout } from "../layout/Layout";
import "./App.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
